// <auto-generated />
namespace SocialGoal.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class AddEquipmentSmart01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEquipmentSmart01));
        
        string IMigrationMetadata.Id
        {
            get { return "201407040758347_AddEquipmentSmart01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
