namespace SocialGoal.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class updateRecData : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.ReceiveDataLasts",
                c => new
                    {
                        ReceiveDataLastId = c.String(nullable: false, maxLength: 128),
                        DevId = c.String(),
                        ReceiveTime = c.DateTime(nullable: false),
                        CollectTime = c.DateTime(nullable: false),
                        TotalWorkTime = c.Long(nullable: false),
                        TotalMileage = c.Long(nullable: false),
                        GpsTime = c.DateTime(nullable: false),
                        GpsIsPos = c.String(),
                        GpsPosProvince = c.String(),
                        GpsPos = c.String(),
                        GpsPlat = c.String(),
                        GpsPlog = c.String(),
                        GpsSpeed = c.String(),
                        GpsDirection = c.String(),
                        GpsElevation = c.String(),
                        GsmSignal = c.String(),
                        CellInformationMain = c.String(),
                        CellInformation1 = c.String(),
                        CellInformation2 = c.String(),
                        CellInformation3 = c.String(),
                        AntennaStatus = c.String(),
                        AccStatus = c.String(),
                        OutStatus = c.String(),
                        SleepStatus = c.String(),
                        AlarmStatus = c.String(),
                        LockStatus = c.String(),
                        F1 = c.String(),
                        F2 = c.String(),
                        F3 = c.String(),
                        F4 = c.String(),
                        F5 = c.String(),
                        F6 = c.String(),
                        F7 = c.String(),
                        F8 = c.String(),
                        F9 = c.String(),
                        F10 = c.String(),
                        F11 = c.String(),
                        F12 = c.String(),
                        F13 = c.String(),
                        F14 = c.String(),
                        F15 = c.String(),
                        F16 = c.String(),
                        F17 = c.String(),
                        F18 = c.String(),
                        F19 = c.String(),
                        F20 = c.String(),
                        F21 = c.String(),
                        F22 = c.String(),
                        F23 = c.String(),
                        F24 = c.String(),
                        F25 = c.String(),
                        F26 = c.String(),
                        F27 = c.String(),
                        F28 = c.String(),
                        F29 = c.String(),
                        F30 = c.String(),
                        F31 = c.String(),
                        F32 = c.String(),
                        F33 = c.String(),
                        F34 = c.String(),
                        F35 = c.String(),
                        F36 = c.String(),
                        F37 = c.String(),
                        F38 = c.String(),
                        F39 = c.String(),
                        F40 = c.String(),
                    })
                .PrimaryKey(t => t.ReceiveDataLastId);
            
            CreateTable(
                "dbo.ReceiveDatas",
                c => new
                    {
                        ReceiveDataId = c.String(nullable: false, maxLength: 128),
                        DevId = c.String(),
                        ReceiveTime = c.DateTime(nullable: false),
                        CollectTime = c.DateTime(nullable: false),
                        TotalWorkTime = c.Long(nullable: false),
                        TotalMileage = c.Long(nullable: false),
                        GpsTime = c.DateTime(nullable: false),
                        GpsIsPos = c.String(),
                        GpsPosProvince = c.String(),
                        GpsPos = c.String(),
                        GpsPlat = c.String(),
                        GpsPlog = c.String(),
                        GpsSpeed = c.String(),
                        GpsDirection = c.String(),
                        GpsElevation = c.String(),
                        GsmSignal = c.String(),
                        CellInformationMain = c.String(),
                        CellInformation1 = c.String(),
                        CellInformation2 = c.String(),
                        CellInformation3 = c.String(),
                        AntennaStatus = c.String(),
                        AccStatus = c.String(),
                        OutStatus = c.String(),
                        SleepStatus = c.String(),
                        AlarmStatus = c.String(),
                        LockStatus = c.String(),
                        F1 = c.String(),
                        F2 = c.String(),
                        F3 = c.String(),
                        F4 = c.String(),
                        F5 = c.String(),
                        F6 = c.String(),
                        F7 = c.String(),
                        F8 = c.String(),
                        F9 = c.String(),
                        F10 = c.String(),
                        F11 = c.String(),
                        F12 = c.String(),
                        F13 = c.String(),
                        F14 = c.String(),
                        F15 = c.String(),
                        F16 = c.String(),
                        F17 = c.String(),
                        F18 = c.String(),
                        F19 = c.String(),
                        F20 = c.String(),
                        F21 = c.String(),
                        F22 = c.String(),
                        F23 = c.String(),
                        F24 = c.String(),
                        F25 = c.String(),
                        F26 = c.String(),
                        F27 = c.String(),
                        F28 = c.String(),
                        F29 = c.String(),
                        F30 = c.String(),
                        F31 = c.String(),
                        F32 = c.String(),
                        F33 = c.String(),
                        F34 = c.String(),
                        F35 = c.String(),
                        F36 = c.String(),
                        F37 = c.String(),
                        F38 = c.String(),
                        F39 = c.String(),
                        F40 = c.String(),
                    })
                .PrimaryKey(t => t.ReceiveDataId);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.ReceiveDatas");
            DropTable("dbo.ReceiveDataLasts");
        }
    }
}
